[package]
name = "n91lib_rs"
version = "0.1.0"
authors = ["noshi91"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
num-traits = "0.2.11"
